FROM --platform=linux/amd64 ubuntu:22.04 as builder

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential libpng-dev

COPY . /repo
WORKDIR /repo/tools
RUN g++ png2stratagus.cpp -lpng -o png2stratagus

FROM ubuntu:22.04 as package
RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y libpng-dev
COPY --from=builder /repo/tools/png2stratagus /
