FROM --platform=linux/amd64 ubuntu:22.04

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential libpng-dev

COPY . /repo
WORKDIR /repo/tools
RUN g++ png2stratagus.cpp -lpng -o png2stratagus
